# data.py — Edit this file to add/remove ingredients and recipes

CATEGORIES = [
    {"id": "grains",     "label": "Grains",      "emoji": "🌾"},
    {"id": "dal",        "label": "Dal",          "emoji": "🫘"},
    {"id": "spices",     "label": "Spices",       "emoji": "🌶️"},
    {"id": "veggies",    "label": "Veggies",      "emoji": "🥦"},
    {"id": "dairy",      "label": "Dairy",        "emoji": "🧈"},
    {"id": "oils",       "label": "Oils",         "emoji": "🫙"},
    {"id": "flour",      "label": "Flour",        "emoji": "🌾"},
    {"id": "frozen",     "label": "Frozen",       "emoji": "❄️"},
    {"id": "snacks",     "label": "Snacks",       "emoji": "🍪"},
    {"id": "beverages",  "label": "Beverages",    "emoji": "☕"},
    {"id": "condiments", "label": "Condiments",   "emoji": "🥫"},
    {"id": "other",      "label": "Other",        "emoji": "📦"},
]

CATEGORY_COLORS = {
    "grains":     "#FFF8E1",
    "dal":        "#FFF0E8",
    "spices":     "#FCE4EC",
    "veggies":    "#E3F8F2",
    "dairy":      "#FFFDE7",
    "oils":       "#F3E5F5",
    "flour":      "#E8F5E9",
    "frozen":     "#E1F5FE",
    "snacks":     "#FFF8E1",
    "beverages":  "#EFEBE9",
    "condiments": "#FCECE8",
    "other":      "#F3E5F5",
}

UNITS = ["kg", "g", "L", "ml", "pcs", "pack", "tbsp", "tsp", "bottle", "can", "bunch"]

INDIAN_STAPLES = [
    {"name": "Basmati Rice",       "cat": "grains",     "qty": 5.0,  "unit": "kg",    "thresh": 1.0},
    {"name": "Atta (Wheat Flour)", "cat": "flour",      "qty": 5.0,  "unit": "kg",    "thresh": 1.0},
    {"name": "Maida",              "cat": "flour",      "qty": 2.0,  "unit": "kg",    "thresh": 0.5},
    {"name": "Besan",              "cat": "flour",      "qty": 1.0,  "unit": "kg",    "thresh": 0.5},
    {"name": "Toor Dal",           "cat": "dal",        "qty": 2.0,  "unit": "kg",    "thresh": 0.5},
    {"name": "Chana Dal",          "cat": "dal",        "qty": 1.0,  "unit": "kg",    "thresh": 0.5},
    {"name": "Moong Dal",          "cat": "dal",        "qty": 1.0,  "unit": "kg",    "thresh": 0.5},
    {"name": "Urad Dal",           "cat": "dal",        "qty": 1.0,  "unit": "kg",    "thresh": 0.5},
    {"name": "Rajma",              "cat": "dal",        "qty": 1.0,  "unit": "kg",    "thresh": 0.5},
    {"name": "Kabuli Chana",       "cat": "dal",        "qty": 1.0,  "unit": "kg",    "thresh": 0.5},
    {"name": "Mustard Seeds",      "cat": "spices",     "qty": 200.0,"unit": "g",     "thresh": 50.0},
    {"name": "Cumin Seeds",        "cat": "spices",     "qty": 200.0,"unit": "g",     "thresh": 50.0},
    {"name": "Turmeric Powder",    "cat": "spices",     "qty": 200.0,"unit": "g",     "thresh": 50.0},
    {"name": "Red Chilli Powder",  "cat": "spices",     "qty": 200.0,"unit": "g",     "thresh": 50.0},
    {"name": "Coriander Powder",   "cat": "spices",     "qty": 150.0,"unit": "g",     "thresh": 50.0},
    {"name": "Garam Masala",       "cat": "spices",     "qty": 100.0,"unit": "g",     "thresh": 30.0},
    {"name": "Cumin Powder",       "cat": "spices",     "qty": 100.0,"unit": "g",     "thresh": 30.0},
    {"name": "Hing (Asafoetida)",  "cat": "spices",     "qty": 50.0, "unit": "g",     "thresh": 10.0},
    {"name": "Bay Leaves",         "cat": "spices",     "qty": 20.0, "unit": "g",     "thresh": 5.0},
    {"name": "Cardamom",           "cat": "spices",     "qty": 50.0, "unit": "g",     "thresh": 10.0},
    {"name": "Cinnamon Sticks",    "cat": "spices",     "qty": 50.0, "unit": "g",     "thresh": 10.0},
    {"name": "Cloves",             "cat": "spices",     "qty": 30.0, "unit": "g",     "thresh": 10.0},
    {"name": "Black Pepper",       "cat": "spices",     "qty": 100.0,"unit": "g",     "thresh": 20.0},
    {"name": "Chat Masala",        "cat": "spices",     "qty": 100.0,"unit": "g",     "thresh": 30.0},
    {"name": "Amchur Powder",      "cat": "spices",     "qty": 100.0,"unit": "g",     "thresh": 25.0},
    {"name": "Ghee",               "cat": "oils",       "qty": 1.0,  "unit": "kg",    "thresh": 0.2},
    {"name": "Mustard Oil",        "cat": "oils",       "qty": 1.0,  "unit": "L",     "thresh": 0.2},
    {"name": "Sunflower Oil",      "cat": "oils",       "qty": 1.0,  "unit": "L",     "thresh": 0.25},
    {"name": "Coconut Oil",        "cat": "oils",       "qty": 500.0,"unit": "ml",    "thresh": 100.0},
    {"name": "Onions",             "cat": "veggies",    "qty": 2.0,  "unit": "kg",    "thresh": 0.5},
    {"name": "Tomatoes",           "cat": "veggies",    "qty": 1.0,  "unit": "kg",    "thresh": 0.3},
    {"name": "Potatoes",           "cat": "veggies",    "qty": 2.0,  "unit": "kg",    "thresh": 0.5},
    {"name": "Garlic",             "cat": "veggies",    "qty": 200.0,"unit": "g",     "thresh": 50.0},
    {"name": "Ginger",             "cat": "veggies",    "qty": 200.0,"unit": "g",     "thresh": 50.0},
    {"name": "Green Chillies",     "cat": "veggies",    "qty": 100.0,"unit": "g",     "thresh": 30.0},
    {"name": "Curry Leaves",       "cat": "veggies",    "qty": 1.0,  "unit": "bunch", "thresh": 1.0},
    {"name": "Coriander Leaves",   "cat": "veggies",    "qty": 1.0,  "unit": "bunch", "thresh": 1.0},
    {"name": "Paneer",             "cat": "dairy",      "qty": 500.0,"unit": "g",     "thresh": 100.0},
    {"name": "Curd (Yogurt)",      "cat": "dairy",      "qty": 500.0,"unit": "g",     "thresh": 100.0},
    {"name": "Milk",               "cat": "dairy",      "qty": 2.0,  "unit": "L",     "thresh": 0.5},
    {"name": "Butter",             "cat": "dairy",      "qty": 200.0,"unit": "g",     "thresh": 50.0},
    {"name": "Cream",              "cat": "dairy",      "qty": 200.0,"unit": "ml",    "thresh": 50.0},
    {"name": "Tea Leaves",         "cat": "beverages",  "qty": 500.0,"unit": "g",     "thresh": 100.0},
    {"name": "Coffee Powder",      "cat": "beverages",  "qty": 200.0,"unit": "g",     "thresh": 50.0},
    {"name": "Sugar",              "cat": "other",      "qty": 2.0,  "unit": "kg",    "thresh": 0.5},
    {"name": "Salt",               "cat": "other",      "qty": 1.0,  "unit": "kg",    "thresh": 0.2},
    {"name": "Tamarind",           "cat": "condiments", "qty": 200.0,"unit": "g",     "thresh": 50.0},
    {"name": "Coconut (Dry)",      "cat": "snacks",     "qty": 2.0,  "unit": "pcs",   "thresh": 1.0},
    {"name": "Poha",               "cat": "grains",     "qty": 500.0,"unit": "g",     "thresh": 100.0},
    {"name": "Vermicelli",         "cat": "grains",     "qty": 400.0,"unit": "g",     "thresh": 100.0},
    {"name": "Semolina (Rava)",    "cat": "grains",     "qty": 500.0,"unit": "g",     "thresh": 100.0},
    {"name": "Sabudana",           "cat": "grains",     "qty": 300.0,"unit": "g",     "thresh": 100.0},
    {"name": "Rice Flour",         "cat": "flour",      "qty": 500.0,"unit": "g",     "thresh": 100.0},
    {"name": "Papad",              "cat": "snacks",     "qty": 1.0,  "unit": "pack",  "thresh": 1.0},
    {"name": "Peanuts",            "cat": "snacks",     "qty": 300.0,"unit": "g",     "thresh": 100.0},
    {"name": "Cashews",            "cat": "snacks",     "qty": 200.0,"unit": "g",     "thresh": 50.0},
    {"name": "Pickle (Achar)",     "cat": "condiments", "qty": 1.0,  "unit": "bottle","thresh": 1.0},
    {"name": "Tomato Ketchup",     "cat": "condiments", "qty": 500.0,"unit": "ml",    "thresh": 100.0},
]

STARTER_ITEMS = [
    "Basmati Rice", "Toor Dal", "Atta (Wheat Flour)", "Ghee",
    "Onions", "Tomatoes", "Potatoes", "Cumin Seeds",
    "Turmeric Powder", "Red Chilli Powder", "Garam Masala",
    "Garlic", "Ginger", "Tea Leaves", "Poha", "Semolina (Rava)",
    "Sugar", "Salt", "Mustard Seeds", "Coriander Powder",
]

RECIPES = [
    {
        "id": "r1", "name": "Dal Tadka", "emoji": "🫘",
        "difficulty": "Easy", "time": "30 min", "servings": 4, "region": "North Indian",
        "needs": ["Toor Dal", "Onions", "Tomatoes", "Garlic", "Ginger", "Cumin Seeds", "Turmeric Powder", "Red Chilli Powder", "Ghee"],
        "steps": [
            "Wash and pressure cook toor dal with turmeric and salt for 3–4 whistles until soft.",
            "Heat ghee in a pan. Add cumin seeds and let them splutter.",
            "Add finely chopped onions, fry until golden brown (8–10 min).",
            "Add ginger-garlic paste, cook 2 min until raw smell goes.",
            "Add chopped tomatoes, red chilli powder, cook till oil separates.",
            "Pour the tadka over cooked dal, add water to consistency, boil 5 min.",
            "Garnish with coriander leaves and a final drizzle of ghee.",
        ],
    },
    {
        "id": "r2", "name": "Aloo Sabzi", "emoji": "🥔",
        "difficulty": "Easy", "time": "20 min", "servings": 4, "region": "North Indian",
        "needs": ["Potatoes", "Onions", "Tomatoes", "Turmeric Powder", "Red Chilli Powder", "Cumin Seeds", "Mustard Oil"],
        "steps": [
            "Boil potatoes, peel and cut into cubes.",
            "Heat mustard oil until smoking point, then lower heat.",
            "Splutter cumin seeds, add chopped onions and fry golden.",
            "Add tomatoes and cook with spices until masala is thick.",
            "Add potato cubes, toss well. Simmer 5 min on low heat.",
            "Garnish with coriander. Serve with roti or rice.",
        ],
    },
    {
        "id": "r3", "name": "Paneer Butter Masala", "emoji": "🧀",
        "difficulty": "Medium", "time": "40 min", "servings": 4, "region": "Punjabi",
        "needs": ["Paneer", "Onions", "Tomatoes", "Butter", "Garam Masala", "Red Chilli Powder", "Coriander Powder", "Cream"],
        "steps": [
            "Blend roasted onions and tomatoes into a smooth paste.",
            "Heat butter in a pan, add the paste and cook 10 min.",
            "Add all spices and cook till butter separates from masala.",
            "Add water or cream to get gravy consistency, simmer 5 min.",
            "Cube paneer and add to gravy, simmer on low heat 5 min.",
            "Finish with cream, garam masala and kasuri methi.",
        ],
    },
    {
        "id": "r4", "name": "Chapati / Roti", "emoji": "🫓",
        "difficulty": "Easy", "time": "20 min", "servings": 6, "region": "All India",
        "needs": ["Atta (Wheat Flour)", "Ghee"],
        "steps": [
            "Take 2 cups atta in a bowl. Add water gradually and knead into soft dough.",
            "Rest the dough for 15–20 minutes covered.",
            "Divide into equal balls, roll each into a thin circle.",
            "Cook on a hot tawa for 30 seconds each side until brown spots appear.",
            "Puff on open flame or press with a cloth for full inflation.",
            "Apply ghee immediately and serve hot.",
        ],
    },
    {
        "id": "r5", "name": "Masala Chai", "emoji": "☕",
        "difficulty": "Easy", "time": "10 min", "servings": 2, "region": "All India",
        "needs": ["Tea Leaves", "Milk", "Ginger", "Sugar"],
        "steps": [
            "Crush ginger and add to 1 cup water. Bring to boil.",
            "Add 1.5 tsp tea leaves and sugar to taste.",
            "Boil for 2 min until water turns deep red-brown.",
            "Add 1 cup milk, simmer until frothy and rich.",
            "Strain into cups and serve hot.",
        ],
    },
    {
        "id": "r6", "name": "Poha", "emoji": "🍚",
        "difficulty": "Easy", "time": "15 min", "servings": 2, "region": "Maharashtrian",
        "needs": ["Poha", "Onions", "Mustard Seeds", "Turmeric Powder", "Mustard Oil", "Green Chillies"],
        "steps": [
            "Rinse poha under cold water in a colander. Drain and let sit for 5 min.",
            "Heat oil in a pan. Splutter mustard seeds.",
            "Add green chillies, curry leaves, then diced onions. Fry until translucent.",
            "Add turmeric and salt. Mix in the soaked poha gently.",
            "Cover and cook on low heat for 2–3 min.",
            "Serve with a squeeze of lemon and sev on top.",
        ],
    },
    {
        "id": "r7", "name": "Upma", "emoji": "🥣",
        "difficulty": "Easy", "time": "20 min", "servings": 2, "region": "South Indian",
        "needs": ["Semolina (Rava)", "Onions", "Mustard Seeds", "Cumin Seeds", "Ghee", "Green Chillies"],
        "steps": [
            "Dry roast rava in a pan on medium heat, stirring constantly, until light golden.",
            "Heat ghee in the same pan. Splutter mustard seeds and cumin.",
            "Add green chillies, curry leaves, then onions — sauté until soft.",
            "Pour in 2.5 cups of water and bring to a rolling boil. Add salt.",
            "Slowly pour in the roasted rava while stirring continuously to avoid lumps.",
            "Reduce heat, cover and cook 2 min. Fluff with a fork and finish with ghee.",
        ],
    },
    {
        "id": "r8", "name": "Chana Masala", "emoji": "🫘",
        "difficulty": "Medium", "time": "45 min", "servings": 4, "region": "Punjabi",
        "needs": ["Kabuli Chana", "Onions", "Tomatoes", "Garam Masala", "Coriander Powder", "Cumin Seeds", "Garlic", "Ginger"],
        "steps": [
            "Soak chana overnight. Pressure cook with tea bag for dark color — 5–6 whistles.",
            "Heat oil, splutter cumin seeds, fry onions until deep golden.",
            "Add ginger-garlic paste and cook until raw smell goes.",
            "Add tomatoes and all spice powders, cook till thick masala forms.",
            "Add boiled chana with some cooking water. Simmer 15 min.",
            "Mash a few chana against the pan to thicken gravy.",
            "Finish with garam masala, lemon juice and coriander.",
        ],
    },
    {
        "id": "r9", "name": "Rajma Chawal", "emoji": "🍛",
        "difficulty": "Medium", "time": "60 min", "servings": 4, "region": "North Indian",
        "needs": ["Rajma", "Basmati Rice", "Onions", "Tomatoes", "Garlic", "Ginger", "Garam Masala", "Cumin Seeds"],
        "steps": [
            "Soak rajma overnight. Pressure cook for 6–8 whistles until very soft.",
            "Make smooth onion-tomato masala with all spices.",
            "Add boiled rajma with liquid, mash a few beans for thick gravy.",
            "Simmer 20 min until gravy is rich and coats the beans.",
            "Cook basmati rice with 1:2 water ratio.",
            "Serve rajma over steaming rice with raw onions and lemon.",
        ],
    },
    {
        "id": "r10", "name": "Besan Cheela", "emoji": "🥞",
        "difficulty": "Easy", "time": "20 min", "servings": 2, "region": "North Indian",
        "needs": ["Besan", "Onions", "Green Chillies", "Turmeric Powder", "Cumin Seeds", "Mustard Oil"],
        "steps": [
            "Mix 1 cup besan with water to make smooth batter — pancake consistency.",
            "Add finely chopped onions, green chillies, cumin, turmeric and salt.",
            "Heat a non-stick pan and grease with oil.",
            "Pour a ladle of batter, spread in circular motion.",
            "Cook on medium heat 2 min each side until golden.",
            "Serve hot with chutney or curd.",
        ],
    },
    {
        "id": "r11", "name": "Sabudana Khichdi", "emoji": "⚪",
        "difficulty": "Easy", "time": "25 min", "servings": 2, "region": "Maharashtrian",
        "needs": ["Sabudana", "Peanuts", "Potatoes", "Cumin Seeds", "Ghee", "Green Chillies"],
        "steps": [
            "Soak sabudana for 4 hours or overnight. Drain completely — must be dry.",
            "Dry roast peanuts, remove skin and crush coarsely.",
            "Heat ghee, splutter cumin seeds, add green chillies.",
            "Add boiled potato cubes and sauté 2 min.",
            "Add sabudana, salt, and crushed peanuts. Toss gently.",
            "Cook on low heat 5 min until sabudana turns translucent.",
            "Add lemon juice and serve with curd.",
        ],
    },
    {
        "id": "r12", "name": "Dum Biryani (Veg)", "emoji": "🍛",
        "difficulty": "Hard", "time": "90 min", "servings": 6, "region": "Hyderabadi",
        "needs": ["Basmati Rice", "Onions", "Tomatoes", "Curd (Yogurt)", "Ghee", "Garam Masala", "Cumin Seeds", "Bay Leaves", "Cardamom", "Cinnamon Sticks", "Cloves"],
        "steps": [
            "Soak basmati rice 30 min. Cook until 70% done — must have bite.",
            "Deep fry onions until dark golden (birista) — this is key to flavour.",
            "Marinate vegetables in curd, spices and half the fried onions for 30 min.",
            "Cook marinated vegetables in oil until semi-dry.",
            "Layer: rice, vegetable masala, fried onions, saffron milk, ghee. Repeat.",
            "Seal with dough or tight lid. Cook on dum (low heat) for 25 min.",
            "Let rest 10 min before opening. Serve gently to keep layers intact.",
        ],
    },
]
